### ISSUE TITLE
Queue on NCA for errored issues

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/newspaper-curation-app#120]
Instead of errored issues (that move outside of the NCA workflow) moving to the problem folder on the server, have another queue in NCA (with a role for access to it) where these issues go. In this queue, users with the corresponding role can look at the issues, the comments log, and do the following:
  
Leave a comment and push back into the metadata entry queue
Push issues out of NCA into the existing problem folder (like how it is now) for further work
    
Issues in the current problem folder take a lot of my time to go through them, read all of the text error messages, and reupload them- either with the processor or SFTP- for them to get back into NCA once the issue has been fixed. AND, the real problem is that students often error/reject issues for things cannot be corrected- like issues with the microfilm quality or missing pages. Although I have explained it over and over again, students do not understand that most of these errors are just the way it is, to put it bluntly. We cannot correct every missing page or quality issue, for in-house scans or SFTP uploads.

**Comment by jechols** [comment]
Forgot to close this - work was done a while ago
