### ISSUE TITLE
Build poppler with libopenjpeg

### ISSUE THREAD

**Issue by techgique** [uoregon-libraries/newspaper-curation-app#163]
From logs while NCA web Docker image is building:
> Building poppler with support for:
>  font configuration: fontconfig
>  splash output: yes
>  cairo output: no (requires cairo >= 1.10.0)
>  qt4 wrapper: no
>  glib wrapper: no (requires cairo output)
>  introspection: no
>  cpp wrapper: yes
>  use gtk-doc: no
>  use libjpeg: yes
>  use libpng: yes
>  use libtiff: no
>  use zlib: no
>  use libcurl: no
>  use libopenjpeg: no
>  use cms: auto
>  command line utils: yes
>  test data dir: /usr/local/poppler-0.22.5/./../test
> 
> Warning: Using libopenjpeg is recommended

Jeremy warns that poppler version changes have been fickle, so we'd want to approach this carefully and test thoroughly.

**Comment by jechols** [comment]
Docker no longer builds poppler from source, and isn't recommended for dev or prod anyway, so this is moot
