### ISSUE TITLE
Stand up NCA demo site

### ISSUE THREAD

**Issue by techgique** [uoregon-libraries/newspaper-curation-app#168]
Initially thought of as just for Nebraska but it could be used by members of the board as well. I'll work to stand this up on our Newspapers dev server with nca-test-data and some scripting (which hopefully can be contributed back to the repo) to reset the environment overnight and/or on demand

**Comment by techgique** [comment]
Demo site up at https://nebnewspapers-dev.unl.edu/nca-demo/ (Apache auth creds shared on Slack)

Need to update to a more recent commit with STFPgo and verify workflow functions with [https://uoregon-libraries.github.io/newspaper-curation-app/contributing/testing/#using-uos-test-issues](test issues). Test issues files are in place in `/test/sources/`.

**Comment by sseymore** [comment]
@techgique Thanks so much. I added the titles for the UO sample batch content. The UNL one will need MARC loaded, probably. Ready to add the issues to NCA. Sample batch content is shared on OneDrive. Slack me if you need the link.

**Comment by techgique** [comment]
Demo site has successfully been updated to tip of `main` branch.

Documentation for deployment is in Google Drive:
- Open ON Workspace > NEH_grant_work > dev_team > documentation > unl-nca-demo-centos7-deployment.md
- https://drive.google.com/file/d/1-U4s0SljPbx7d8hgVOTp9wtgwZmgHSb6/view?usp=sharing

Test issues from UO GitHub repo and Smoke Signals sample batch are in place via the `test/reset.sh` approach and visible in "Uploaded Titles".

May have a bug or misconfiguration as both my local instance and the demo site seem to rewrite the `.manifest` files to have the current date and time every minute. Running `test/make-older.sh` and manually editing the date in the files is overwritten at each minute so titles are never seen as old enough by NCA.

**Comment by techgique** [comment]
Remaining issue moved to a new ticket: https://github.com/uoregon-libraries/newspaper-curation-app/issues/214
