### ISSUE TITLE
SFTPGo: use API keys instead of JWT

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/newspaper-curation-app#192]
JWT is a very poor model for automated connectivity:

- We're forced to store an admin's password *in plain text* in our settings file. This file shouldn't be accessible to anybody, obviously, but it's still a bad idea and a bad practice. (We could encrypt the password in our settings file, but NCA has to have it in plain text eventually, which means NCA would need the decryption key... in the settings file....)
- We have to refresh the JWT regularly, which complicates NCA - every RPC request has to start by checking if the token needs to be refreshed.

An API key is much better in theory, because most apps which implement them give you a way to specify per-key permissions, a UI to easily get rid of keys if you suspect one is compromised (or simply no longer in use), etc. SFTPGo's author, however, has been opposed to API keys on the principal that they're "intrinsically less secure" than JWT: https://github.com/drakkan/sftpgo/discussions/400. This resulted in an API key implementation that's a lot less full-featured than we'd prefer: we can't specify per-key permissions, and all keys have to be created by manually using the JWT-based REST API. Additionally, it's easy to revoke *all* keys without meaning to in the actual web UI.

This all combines to make API keys complicated. It's still the right choice (storing a key that's easily revoked instead of a password), but end-user docs will need to be built carefully. We'll need to explain very clearly how to provision a key, how to remove a key (I believe individual keys can only be removed via the API itself), and how to ensure you don't accidentally revoke key use since the web UI only lets you specify *if* you allow keys at all, but doesn't have granular control.

**Comment by jechols** [comment]
Docs for adding API keys: https://sftpgo.stoplight.io/docs/sftpgo/31edeaa868de9-add-api-key

**Comment by techgique** [comment]
From docs: https://github.com/drakkan/sftpgo/blob/main/docs/rest-api.md

> API keys are not allowed for the following REST APIs:
>   - manage API keys itself. You cannot create, update, delete, enumerate API keys if you are logged in with an API key
>   - change password, public keys or second factor authentication for the associated user
>   - update the impersonated admin

Are these limitations going to be a problem in terms of still requiring JWT use for these REST API features? I'm guessing the middle one if any might be needed for NCA?

**Comment by jechols** [comment]
I don't *think* so, but if it turns out I'm wrong, we just have to abandon this ticket. But I believe the docs are stating that the user who has an API key can't use it to update themselves, which is fine since our plan is to use the API key to manage others' data. If my interpretation is wrong, we're hosed and that'll irritate me, but then we'll just keep doing what we already are.
