### ISSUE TITLE
Add filtering to workflow pages

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/newspaper-curation-app#95]
To allow an easier time finding specific issues, we should add a variety of filter options, including at least the following:

- Title (dropdown like issue finder or implement a nicer typeahead that will require some a11y investigations?)
- Language (when it's merged)

It may be worth asking students what other filters might be useful.

These filters could reload the page entirely (easy) or refine the page's results (less easy - accessibility will need some care)

**Comment by jechols** [comment]
Filtering by awardee (marc org code) could also be beneficial since the non-oru awardees tend to be the ones with deadlines

**Comment by sseymore** [comment]
Boosting this one-- would be very useful!
